global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "iot_controller"
    static_configs:
      - targets: ["iot_controller:8000"]

  - job_name: "rule_engine"
    static_configs:
      - targets: ["rule_engine:8001"]
